apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dockerize
  name: dockerize
  namespace: app-dockerize
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: dockerize
status:
  loadBalancer: {}
